// <auto-generated />
using System;
using COMP2139_assign01.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace COMP2139_assign01.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250412002423_Update")]
    partial class Update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("COMP2139_assign01.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "Electronic devices and accessories",
                            Name = "Electronics"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "Books and educational materials",
                            Name = "Books"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "Apparel and fashion items",
                            Name = "Clothing"
                        },
                        new
                        {
                            CategoryId = 4,
                            Description = "Home and kitchen appliances",
                            Name = "Home & Kitchen"
                        },
                        new
                        {
                            CategoryId = 5,
                            Description = "Sports equipment and outdoor gear",
                            Name = "Sports & Outdoors"
                        },
                        new
                        {
                            CategoryId = 6,
                            Description = "Toys, games, and entertainment items",
                            Name = "Toys & Games"
                        },
                        new
                        {
                            CategoryId = 7,
                            Description = "Beauty and personal care products",
                            Name = "Beauty & Personal Care"
                        },
                        new
                        {
                            CategoryId = 8,
                            Description = "Office and stationery items",
                            Name = "Office Supplies"
                        },
                        new
                        {
                            CategoryId = 9,
                            Description = "Pet food and accessories",
                            Name = "Pet Supplies"
                        },
                        new
                        {
                            CategoryId = 10,
                            Description = "Car accessories and maintenance items",
                            Name = "Automotive"
                        });
                });

            modelBuilder.Entity("COMP2139_assign01.Models.Inventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InventoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("TotalStock")
                        .HasColumnType("integer");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("InventoryId");

                    b.ToTable("Inventory");
                });

            modelBuilder.Entity("COMP2139_assign01.Models.InventoryTask", b =>
                {
                    b.Property<int>("InventoryTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InventoryTaskId"));

                    b.Property<int>("InventoryId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("InventoryTaskId");

                    b.HasIndex("InventoryId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("COMP2139_assign01.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderId"));

                    b.Property<string>("GuestEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GuestPhone")
                        .HasColumnType("text");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("text");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("COMP2139_assign01.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("COMP2139_assign01.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("LowStockThreshold")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Description = "High-quality wireless earbuds with noise cancellation",
                            LowStockThreshold = 10,
                            Name = "Wireless Earbuds",
                            Price = 79.99m,
                            Quantity = 49,
                            SKU = "ELEC-001"
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            Description = "Feature-rich smartwatch with health tracking",
                            LowStockThreshold = 8,
                            Name = "Smart Watch",
                            Price = 199.99m,
                            Quantity = 45,
                            SKU = "ELEC-002"
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            Description = "Portable Bluetooth speaker with great sound",
                            LowStockThreshold = 12,
                            Name = "Bluetooth Speaker",
                            Price = 49.99m,
                            Quantity = 38,
                            SKU = "ELEC-003"
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 1,
                            Description = "Fast-charging USB-C power adapter",
                            LowStockThreshold = 15,
                            Name = "USB-C Charger",
                            Price = 24.99m,
                            Quantity = 41,
                            SKU = "ELEC-004"
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 1,
                            Description = "Ergonomic wireless mouse",
                            LowStockThreshold = 10,
                            Name = "Wireless Mouse",
                            Price = 29.99m,
                            Quantity = 38,
                            SKU = "ELEC-005"
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 2,
                            Description = "Comprehensive programming guide",
                            LowStockThreshold = 7,
                            Name = "The Art of Programming",
                            Price = 39.99m,
                            Quantity = 7,
                            SKU = "BOOK-001"
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 2,
                            Description = "Introduction to data science",
                            LowStockThreshold = 7,
                            Name = "Data Science Basics",
                            Price = 29.99m,
                            Quantity = 5,
                            SKU = "BOOK-002"
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 2,
                            Description = "Modern web development techniques",
                            LowStockThreshold = 7,
                            Name = "Web Development Guide",
                            Price = 34.99m,
                            Quantity = 11,
                            SKU = "BOOK-003"
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 2,
                            Description = "AI and ML fundamentals",
                            LowStockThreshold = 7,
                            Name = "AI & Machine Learning",
                            Price = 44.99m,
                            Quantity = 13,
                            SKU = "BOOK-004"
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 2,
                            Description = "Introduction to cloud computing",
                            LowStockThreshold = 7,
                            Name = "Cloud Computing 101",
                            Price = 32.99m,
                            Quantity = 33,
                            SKU = "BOOK-005"
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 3,
                            Description = "Comfortable cotton t-shirt",
                            LowStockThreshold = 15,
                            Name = "Cotton T-Shirt",
                            Price = 19.99m,
                            Quantity = 45,
                            SKU = "CLTH-001"
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 3,
                            Description = "Classic denim jeans",
                            LowStockThreshold = 10,
                            Name = "Denim Jeans",
                            Price = 49.99m,
                            Quantity = 27,
                            SKU = "CLTH-002"
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 3,
                            Description = "Warm hooded sweatshirt",
                            LowStockThreshold = 12,
                            Name = "Hooded Sweatshirt",
                            Price = 39.99m,
                            Quantity = 13,
                            SKU = "CLTH-003"
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 3,
                            Description = "Comfortable running shoes",
                            LowStockThreshold = 8,
                            Name = "Running Shoes",
                            Price = 89.99m,
                            Quantity = 25,
                            SKU = "CLTH-004"
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 3,
                            Description = "Warm winter jacket",
                            LowStockThreshold = 8,
                            Name = "Winter Jacket",
                            Price = 129.99m,
                            Quantity = 8,
                            SKU = "CLTH-005"
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 4,
                            Description = "Programmable coffee maker",
                            LowStockThreshold = 8,
                            Name = "Coffee Maker",
                            Price = 79.99m,
                            Quantity = 43,
                            SKU = "HOME-001"
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = 4,
                            Description = "Multi-function toaster oven",
                            LowStockThreshold = 8,
                            Name = "Toaster Oven",
                            Price = 69.99m,
                            Quantity = 30,
                            SKU = "HOME-002"
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryId = 4,
                            Description = "High-speed blender",
                            LowStockThreshold = 10,
                            Name = "Blender",
                            Price = 49.99m,
                            Quantity = 16,
                            SKU = "HOME-003"
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryId = 4,
                            Description = "Complete cookware set",
                            LowStockThreshold = 6,
                            Name = "Cookware Set",
                            Price = 149.99m,
                            Quantity = 5,
                            SKU = "HOME-004"
                        },
                        new
                        {
                            ProductId = 20,
                            CategoryId = 4,
                            Description = "Professional kitchen knife set",
                            LowStockThreshold = 7,
                            Name = "Kitchen Knife Set",
                            Price = 89.99m,
                            Quantity = 47,
                            SKU = "HOME-005"
                        },
                        new
                        {
                            ProductId = 21,
                            CategoryId = 5,
                            Description = "Non-slip yoga mat",
                            LowStockThreshold = 12,
                            Name = "Yoga Mat",
                            Price = 24.99m,
                            Quantity = 12,
                            SKU = "SPRT-001"
                        },
                        new
                        {
                            ProductId = 22,
                            CategoryId = 5,
                            Description = "Adjustable dumbbells set",
                            LowStockThreshold = 8,
                            Name = "Dumbbells Set",
                            Price = 79.99m,
                            Quantity = 6,
                            SKU = "SPRT-002"
                        },
                        new
                        {
                            ProductId = 23,
                            CategoryId = 5,
                            Description = "Professional tennis racket",
                            LowStockThreshold = 8,
                            Name = "Tennis Racket",
                            Price = 59.99m,
                            Quantity = 40,
                            SKU = "SPRT-003"
                        },
                        new
                        {
                            ProductId = 24,
                            CategoryId = 5,
                            Description = "Indoor/outdoor basketball",
                            LowStockThreshold = 10,
                            Name = "Basketball",
                            Price = 29.99m,
                            Quantity = 5,
                            SKU = "SPRT-004"
                        },
                        new
                        {
                            ProductId = 25,
                            CategoryId = 5,
                            Description = "4-person camping tent",
                            LowStockThreshold = 6,
                            Name = "Camping Tent",
                            Price = 199.99m,
                            Quantity = 38,
                            SKU = "SPRT-005"
                        },
                        new
                        {
                            ProductId = 26,
                            CategoryId = 6,
                            Description = "Classic board games collection",
                            LowStockThreshold = 10,
                            Name = "Board Game Set",
                            Price = 34.99m,
                            Quantity = 33,
                            SKU = "TOYS-001"
                        },
                        new
                        {
                            ProductId = 27,
                            CategoryId = 6,
                            Description = "High-speed RC car",
                            LowStockThreshold = 8,
                            Name = "Remote Control Car",
                            Price = 44.99m,
                            Quantity = 35,
                            SKU = "TOYS-002"
                        },
                        new
                        {
                            ProductId = 28,
                            CategoryId = 6,
                            Description = "Creative building blocks set",
                            LowStockThreshold = 12,
                            Name = "Building Blocks",
                            Price = 29.99m,
                            Quantity = 45,
                            SKU = "TOYS-003"
                        },
                        new
                        {
                            ProductId = 29,
                            CategoryId = 6,
                            Description = "1000-piece puzzle set",
                            LowStockThreshold = 15,
                            Name = "Puzzle Set",
                            Price = 19.99m,
                            Quantity = 28,
                            SKU = "TOYS-004"
                        },
                        new
                        {
                            ProductId = 30,
                            CategoryId = 6,
                            Description = "Complete art supply kit",
                            LowStockThreshold = 10,
                            Name = "Art Supply Kit",
                            Price = 24.99m,
                            Quantity = 11,
                            SKU = "TOYS-005"
                        },
                        new
                        {
                            ProductId = 31,
                            CategoryId = 7,
                            Description = "Professional hair dryer",
                            LowStockThreshold = 10,
                            Name = "Hair Dryer",
                            Price = 49.99m,
                            Quantity = 31,
                            SKU = "BEAU-001"
                        },
                        new
                        {
                            ProductId = 32,
                            CategoryId = 7,
                            Description = "Sonic electric toothbrush",
                            LowStockThreshold = 12,
                            Name = "Electric Toothbrush",
                            Price = 39.99m,
                            Quantity = 43,
                            SKU = "BEAU-002"
                        },
                        new
                        {
                            ProductId = 33,
                            CategoryId = 7,
                            Description = "Hydrating face moisturizer",
                            LowStockThreshold = 15,
                            Name = "Face Moisturizer",
                            Price = 24.99m,
                            Quantity = 39,
                            SKU = "BEAU-003"
                        },
                        new
                        {
                            ProductId = 34,
                            CategoryId = 7,
                            Description = "Premium shampoo and conditioner",
                            LowStockThreshold = 15,
                            Name = "Shampoo Set",
                            Price = 29.99m,
                            Quantity = 8,
                            SKU = "BEAU-004"
                        },
                        new
                        {
                            ProductId = 35,
                            CategoryId = 7,
                            Description = "Professional makeup kit",
                            LowStockThreshold = 8,
                            Name = "Makeup Kit",
                            Price = 59.99m,
                            Quantity = 31,
                            SKU = "BEAU-005"
                        },
                        new
                        {
                            ProductId = 36,
                            CategoryId = 8,
                            Description = "Multi-compartment desk organizer",
                            LowStockThreshold = 12,
                            Name = "Desk Organizer",
                            Price = 19.99m,
                            Quantity = 9,
                            SKU = "OFFC-001"
                        },
                        new
                        {
                            ProductId = 37,
                            CategoryId = 8,
                            Description = "Premium notebook set",
                            LowStockThreshold = 15,
                            Name = "Notebook Set",
                            Price = 14.99m,
                            Quantity = 46,
                            SKU = "OFFC-002"
                        },
                        new
                        {
                            ProductId = 38,
                            CategoryId = 8,
                            Description = "High-quality printer paper",
                            LowStockThreshold = 20,
                            Name = "Printer Paper",
                            Price = 9.99m,
                            Quantity = 14,
                            SKU = "OFFC-003"
                        },
                        new
                        {
                            ProductId = 39,
                            CategoryId = 8,
                            Description = "Luxury pen set",
                            LowStockThreshold = 20,
                            Name = "Pen Set",
                            Price = 7.99m,
                            Quantity = 23,
                            SKU = "OFFC-004"
                        },
                        new
                        {
                            ProductId = 40,
                            CategoryId = 8,
                            Description = "Heavy-duty stapler",
                            LowStockThreshold = 15,
                            Name = "Stapler",
                            Price = 8.99m,
                            Quantity = 40,
                            SKU = "OFFC-005"
                        },
                        new
                        {
                            ProductId = 41,
                            CategoryId = 9,
                            Description = "Comfortable dog bed",
                            LowStockThreshold = 8,
                            Name = "Dog Bed",
                            Price = 39.99m,
                            Quantity = 46,
                            SKU = "PETS-001"
                        },
                        new
                        {
                            ProductId = 42,
                            CategoryId = 9,
                            Description = "Self-cleaning litter box",
                            LowStockThreshold = 10,
                            Name = "Cat Litter Box",
                            Price = 29.99m,
                            Quantity = 44,
                            SKU = "PETS-002"
                        },
                        new
                        {
                            ProductId = 43,
                            CategoryId = 9,
                            Description = "Stainless steel food bowl",
                            LowStockThreshold = 15,
                            Name = "Pet Food Bowl",
                            Price = 14.99m,
                            Quantity = 27,
                            SKU = "PETS-003"
                        },
                        new
                        {
                            ProductId = 44,
                            CategoryId = 9,
                            Description = "Assorted pet toys",
                            LowStockThreshold = 12,
                            Name = "Pet Toys Set",
                            Price = 19.99m,
                            Quantity = 13,
                            SKU = "PETS-004"
                        },
                        new
                        {
                            ProductId = 45,
                            CategoryId = 9,
                            Description = "Portable pet carrier",
                            LowStockThreshold = 8,
                            Name = "Pet Carrier",
                            Price = 49.99m,
                            Quantity = 39,
                            SKU = "PETS-005"
                        },
                        new
                        {
                            ProductId = 46,
                            CategoryId = 10,
                            Description = "Universal car phone mount",
                            LowStockThreshold = 12,
                            Name = "Car Phone Mount",
                            Price = 19.99m,
                            Quantity = 10,
                            SKU = "AUTO-001"
                        },
                        new
                        {
                            ProductId = 47,
                            CategoryId = 10,
                            Description = "Portable car vacuum",
                            LowStockThreshold = 10,
                            Name = "Car Vacuum Cleaner",
                            Price = 39.99m,
                            Quantity = 13,
                            SKU = "AUTO-002"
                        },
                        new
                        {
                            ProductId = 48,
                            CategoryId = 10,
                            Description = "Long-lasting air freshener",
                            LowStockThreshold = 20,
                            Name = "Car Air Freshener",
                            Price = 7.99m,
                            Quantity = 22,
                            SKU = "AUTO-003"
                        },
                        new
                        {
                            ProductId = 49,
                            CategoryId = 10,
                            Description = "Digital tire pressure gauge",
                            LowStockThreshold = 15,
                            Name = "Tire Pressure Gauge",
                            Price = 12.99m,
                            Quantity = 12,
                            SKU = "AUTO-004"
                        },
                        new
                        {
                            ProductId = 50,
                            CategoryId = 10,
                            Description = "Complete car wash kit",
                            LowStockThreshold = 10,
                            Name = "Car Wash Kit",
                            Price = 29.99m,
                            Quantity = 26,
                            SKU = "AUTO-005"
                        });
                });

            modelBuilder.Entity("COMP2139_assign01.Models.InventoryTask", b =>
                {
                    b.HasOne("COMP2139_assign01.Models.Inventory", "Inventory")
                        .WithMany("Tasks")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("COMP2139_assign01.Models.OrderItem", b =>
                {
                    b.HasOne("COMP2139_assign01.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("COMP2139_assign01.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("COMP2139_assign01.Models.Product", b =>
                {
                    b.HasOne("COMP2139_assign01.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("COMP2139_assign01.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("COMP2139_assign01.Models.Inventory", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("COMP2139_assign01.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("COMP2139_assign01.Models.Product", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
