// <auto-generated />
using COMP2139_assign01.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace COMP2139_assign01.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("COMP2139_assign01.Models.Inventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InventoryId"));

                    b.Property<int?>("InventoryId1")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("TotalStock")
                        .HasColumnType("integer");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("InventoryId");

                    b.HasIndex("InventoryId1");

                    b.ToTable("Inventory");

                    b.HasData(
                        new
                        {
                            InventoryId = 1,
                            Name = "Carpet",
                            Price = 50m,
                            Quantity = 5,
                            TotalStock = 0,
                            category = "Household"
                        },
                        new
                        {
                            InventoryId = 2,
                            Name = "Laptop",
                            Price = 500m,
                            Quantity = 7,
                            TotalStock = 0,
                            category = "Electronics"
                        });
                });

            modelBuilder.Entity("COMP2139_assign01.Models.InventoryTask", b =>
                {
                    b.Property<int>("InventoryTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InventoryTaskId"));

                    b.Property<int>("InventoryId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("InventoryTaskId");

                    b.HasIndex("InventoryId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("COMP2139_assign01.Models.Inventory", b =>
                {
                    b.HasOne("COMP2139_assign01.Models.Inventory", null)
                        .WithMany("LowStockItems")
                        .HasForeignKey("InventoryId1");
                });

            modelBuilder.Entity("COMP2139_assign01.Models.InventoryTask", b =>
                {
                    b.HasOne("COMP2139_assign01.Models.Inventory", "Inventory")
                        .WithMany("Tasks")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("COMP2139_assign01.Models.Inventory", b =>
                {
                    b.Navigation("LowStockItems");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
